export const actionTypes = {
    REPOSITORIES_FETCH_INITIATED: "REPOSITORIES_FETCH_INITIATED",
    REPOSITORIES_FETCH_SUCCEEDED: "REPOSITORIES_FETCH_SUCCEEDED",
    REPOSITORIES_FETCH_FAILED: "REPOSITORIES_FETCH_FAILED",
    REPOSITORY_REDIRECT: "REPOSITORY_REDIRECT",
};